config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  get '/pessoas', to: 'pessoas#index'
  get '/pessoas/nova', to: 'pessoas#new' 
  post '/pessoas', to: 'pessoas#create' 
  resources :pessoas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
    mount_uploader :arquivo, ArquivoUploader
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  def index
    @pessoas = Pessoa.all
  end

  def new
    @pessoa = Pessoa.new
  end

  def create
    @pessoa = Pessoa.new(pessoa_params)
    @pessoa.tem_arquivo = params[:pessoa][:arquivo].present? && params[:pessoa][:arquivo].respond_to?(:file?)
  
    if @pessoa.save
      redirect_to pessoas_path, notice: 'Pessoa adicionada com sucesso!'
    else
      render 'new'
    end
  end

  def edit
    @pessoa = Pessoa.find(params[:id])
  end

  def update
    @pessoa = Pessoa.find(params[:id])
    if @pessoa.update(pessoa_params)
      render json: { id: @pessoa.id, rowHtml: render_to_string(partial: 'table_row', locals: { pessoa: @pessoa }) }
    else
      render :edit
    end
  end

  def show
    @pessoa = Pessoa.find(params[:id])
  end

  def destroy
    @pessoa = Pessoa.find(params[:id])
    @pessoa.destroy
  
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa removida com sucesso!' }
      format.js   { head :no_content }
    end
  end

  private

  def pessoa_params
    params.require(:pessoa).permit(:nome, :sobrenome, :idade, :arquivo, :sexo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Le</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="styles.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% flash.each do |key, value| %>
      <div class="flash-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pessoas/_form.html.erb
<!-- app/views/pessoas/_form.html.erb -->
<%= form_for pessoa, url: pessoa.persisted? ? pessoa_path(pessoa) : pessoas_path, html: { method: pessoa.persisted? ? :patch : :post, multipart: true, id: 'edit_pessoa' } do |f| %>
  <!-- Primeira Linha -->
  <div class="form1">
    <div class="form-group">
      <%= f.label :nome %>
      <%= f.text_field :nome %>
    </div>

    <div class="form-group">
      <%= f.label :sobrenome %>
      <%= f.text_field :sobrenome %>
    </div>
  </div>

  <!-- Segunda Linha -->
  <div class="form2">
    <div class="form-group">
      <%= f.label :idade %>
      <%= f.number_field :idade %>
    </div>

    <div class="form-group">
      <%= f.label :sexo %>
      <div class="radio-btn">
        <%= f.collection_radio_buttons :sexo, [['Masculino', 'Masculino'], ['Feminino', 'Feminino'], ['Outro', 'outro']], :last, :first %>
      </div>
    </div>
  </div>

  <!-- Terceira Linha -->
  <div class="form3">
    <div>
      <%= f.label :arquivo %>
      <%= f.file_field :arquivo %>
    </div>
  </div>

  <!-- Quarta Linha -->
  <div class="form4">
    <div class="form-group">
      <%= link_to 'Voltar', pessoas_path, class: 'btn-back' %>
    </div>
    <div class="form-group">
      <%= f.submit pessoa.persisted? ? "Atualizar" : "Salvar", class: 'btn-save' %>
    </div>
  </div>
<% end %>

app/views/pessoas/_table.html.erb
<!-- app/views/pessoas/_table.html.erb -->
<% @pessoas.each do |pessoa| %>
  <tr>
    <td><%= pessoa.nome %></td>
    <td><%= pessoa.sobrenome %></td>
    <td><%= pessoa.idade %></td>
    <td><%= pessoa.sexo %></td>
    <td><%= pessoa.tem_arquivo ? 'Sim' : 'Não' %></td>
    <td>
      <%= link_to 'Editar', edit_pessoa_path(pessoa) %>
      <%= link_to 'Deletar', pessoa_path(pessoa), method: :delete, data: { confirm: 'Tem certeza?' } %>
    </td>
  </tr>
<% end %>

app/views/pessoas/_table_row.html.erb
<!-- app/views/pessoas/_table_row.html.erb -->
<tr id="pessoa_<%= pessoa.id %>">
  <td><%= pessoa.nome %></td>
  <td><%= pessoa.sobrenome %></td>
  <td><%= pessoa.idade %></td>
  <td><%= pessoa.sexo %></td>
  <td><%= pessoa.tem_arquivo ? 'Sim' : 'Não' %></td>
  <td>
    <%= link_to 'Editar', edit_pessoa_path(pessoa) %>
    <%= link_to 'Deletar', pessoa_path(pessoa), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'delete-button' %>
  </td>
</tr>

app/views/pessoas/edit.html.erb
<!-- app/views/pessoas/edit.html.erb -->
<h1>Editar Pessoa</h1>

<%= render 'form', pessoa: @pessoa, remote: true %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('edit_pessoa');
    form.addEventListener('ajax:success', function(event) {
      const [data, status, xhr] = event.detail;
      const responseData = JSON.parse(xhr.response);
      const updatedRow = document.getElementById(`pessoa_${responseData.id}`);
      updatedRow.innerHTML = responseData.rowHtml;
    });
  });
</script>

app/views/pessoas/index.html.erb
<!-- app/views/pessoas/index.html.erb -->
<h1>Listagem de Pessoas</h1>

<%= link_to "Adicionar Pessoa", new_pessoa_path, class: "adicionar-pessoa-btn" %>

<!-- Tabela para listar as pessoas -->
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Idade</th>
      <th>Sexo</th>
      <th>Arquivo Anexado</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'table_row', collection: @pessoas, as: :pessoa %>
  </tbody>
</table>

app/views/pessoas/new.html.erb
<!-- app/views/pessoas/new.html.erb -->
<h1>Adicionar Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

app/views/pessoas/show.html.erb
<!-- app/views/pessoas/show.html.erb -->
<h1>Detalhes da Pessoa</h1>

<table>
    <thead>
        <tr>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Idade</th>
        <th>Sexo</th>
        <th>Arquivo Anexado</th>
        </tr>
    </thead>
    <tr>
    <td><%= @pessoa.nome %></td>
    <td><%= @pessoa.sobrenome %></td>
    <td><%= @pessoa.idade %></td>
    <td><%= @pessoa.sexo %></td>
    <td><%= @pessoa.tem_arquivo ? 'Sim' : 'Não' %></td>
    </tr>
</table>
<%= form_for @pessoa, method: :delete, url: pessoa_path(@pessoa) do |f| %>
  <%= f.submit 'Confirmar Exclusão', data: { confirm: 'Tem certeza?' } %>
  <%= link_to 'Voltar', pessoas_path, class: 'btn-back' %>
<% end %>